from uuid import UUID
from sqlmodel import Field, text
from ..models import UserBase


class Users(UserBase, table=True):
    """docstring for Users."""
    # Postgres will generate the UUID (version 7) for us instead of manual defining it
    id: UUID | None = Field(
        default=None,
        primary_key=True,
        sa_column_kwargs={
            "server_default": text(text="uuidv7()"),
            "nullable": False
        }
    )
    # usr_role_id: int = Field(default=None, foreign_key=True)
    pwd: str


class UserPublic(UserBase):
    """docstring for UserPublic."""
    # Hint for testers that these columns won't be appear in body as it's
    # generated by database
    id: UUID
    # usr_role_id: int = Field(default=None, foreign_key=True)


class UserCreate(UserBase):
    """docstring for UserCreate."""
    # Hint for testers that these columns are extra needed during a POST request
    pwd: str


class UserUpdate(UserBase):
    """docstring for UserUpdate."""
    # Bypass the check from 'pyright' so it works with with what the FastAPI
    # documentation said here:
    # https://fastapi.tiangolo.com/tutorial/sql-databases
    name:   str | None = None # type: ignore
    email:  str | None = None
    pwd:    str | None = None
