chess:
  stockfish_path: ''
doc_directory: ''
document_path: []
is_quantized: false
llm_name: ollama:qwen2.5
query_analyser:
  is_quantized: false
  llm_name: ollama:qwen2.5
rag:
  retrieve_score_threshold: 0.7
  topk: 10
  vector_db_path: backend/data/vector_db_cosmic
sameasabove: true
seed: 0
service:
- 3
