# Supported base LLMs:
# mistral-7b-v0.1, mistral-7b-instruct-v0.1, mistral-7b-finetuned,
# gemma-7b, gemma-7b-it,
# gpt-3.5-turbo, gpt-4o.

llm_name: "gpt-4o"
is_quantized: True
seed: 0  # seed of response generation by base LLM.
doc_directory: ""  # directory containing .pdf documents to build the system's vector database.
document_path: []  # a string or a list of .pdf to add context to the vector database.

query_analyser:
  llm_name: "gpt-4o"
  seed: 0
  is_quantized: True

chess:
  stockfish_path: ""  # if empty, default to "third_party/stockfish/stockfish-ubuntu-x86-64-avx2"

rag: # RAG-related config.
  topk: 5  # retrieve topk documents.
  retrieve_score_threshold: 0.7  # similarity score under this threshold will not be used in prompt.