# These are supported funding model platforms

github: Adnan525, zwxu064
patreon: Carlos Kuhn
community_bridge: OpenSI
buy_me_a_coffee: OpenSI_cafe
custom: https://payments.canberra.edu.au/Misc/tran?tran-type=OPENSI
