# -------------------------------------------------------------------------------------------------------------
# File: compose.yaml
# Project: Open Source Institute-Cognitive System of Machine Intelligent Computing (OpenSI-CoSMIC)
# Contributors:
#     Bing Tran <binhsan1307@gmail.com>
#
# Copyright (c) 2026 Open Source Institute
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without
# limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so, subject to the following
# conditions:
# 
# The above copyright notice and this permission notice shall be included in all copies or substantial
# portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
# LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# -------------------------------------------------------------------------------------------------------------


name: OpenSI-CoSMIC


services:
  # TODO: swap to Yarn setup due to FE more used to it
  # frontend:
  #   container_name: cosmic-react
  #   restart: unless-stopped
  #   build:
  #     context: ./
  #     dockerfile: ./docker/dockerfiles/react.Dockerfile
  #   ports:
  #     - name: cosmic-vite
  #       target: 5173
  #       host_ip: 127.0.0.1
  #       published: "5174"
  #       protocol: tcp
  #       app_protocol: http
  #       mode: host
  #   networks:
  #       - cosmic-public


  backend:
    container_name: cosmic-fastapi
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/fastapi.Dockerfile
    # NOTE:
    # Live mounting for auto reload on dev only. Remove it and the
    # corresponding top-level volume on prod.
    volumes:
      - type: bind
        source: ./backend
        target: /app
        # NOTE:
        # This makes `.venv` directory container-native at runtime and not
        # trying to bypass the ignore at build time. This's very important when
        # you do the development in Windows.
      - type: volume
        source: cosmic-fastapi-venv
        target: /app/.venv
    ports:
      - name: cosmic-uvicorn
        target: 8000
        host_ip: 127.0.0.1
        published: "8001"
        protocol: tcp
        app_protocol: http
        mode: host
    networks:
        - cosmic-public
        - cosmic-private


  database:
    container_name: cosmic-postgres
    depends_on:
      backend:
        restart: true
        condition: service_started
        required: true
    restart: unless-stopped
    # Set shared memory limit when using docker compose
    shm_size: 128mb
    secrets:
      - source: cosmic-postgres-user
        target: usr.txt
      - source: cosmic-postgres-database
        target: db.txt
      - source: cosmic-postgres-password
        target: pwd.txt
    environment:
        POSTGRES_USER_FILE: /run/secrets/usr.txt
        POSTGRES_DB_FILE: /run/secrets/db.txt
        POSTGRES_PASSWORD_FILE: /run/secrets/pwd.txt
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/postgres.Dockerfile
    volumes:
      - type: volume
        source: cosmic-postgres-data
        target: /var/lib/postgresql
    networks:
        - cosmic-private


  gui:
    container_name: cosmic-pgadmin
    depends_on:
      backend:
        restart: true
        condition: service_started
        required: true
      database:
        restart: true
        condition: service_started
        required: true
    restart: unless-stopped
    secrets:
      - source: cosmic-pgadmin-password
        target: pwd.txt
    environment:
        # NOTE: Make sure to enable 2FA for this account on prod
        PGADMIN_DEFAULT_EMAIL: opensi@canberra.edu.au
        PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pwd.txt
    configs:
      - source: cosmic-pgadmin-server
        target: /pgadmin4/servers.json
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/pgadmin.Dockerfile
    volumes:
      - type: volume
        source: cosmic-pgadmin-data
        target: /var/lib/pgadmin
    ports:
      - name: cosmic-pgadmin-gunicorn
        target: 80
        host_ip: 127.0.0.1
        published: "5050"
        protocol: tcp
        app_protocol: http
        mode: host
    networks:
      - cosmic-private


  ollama:
    container_name: cosmic-ollama
    depends_on:
      backend:
        restart: true
        condition: service_started
        required: true
    restart: unless-stopped
    # NOTE:
    # If you've GPU installed on your machine AND it's running Linux/MacOS
    # (this's very important), comment out current Dockerfile and use the
    # following:
    # 1. NVIDIA GPU
    # build:
    #   context: ./
    #   dockerfile: ./docker/dockerfile/ollama/ollama.nvida_cpu.Dockerfile
    # model:
    #   gpus: all
    # 2. AMD GPU
    # build:
    #   context: ./
    #   dockerfile: ./docker/dockerfile/ollama/ollama.amd_cpu.Dockerfile
    # devices:
    #   - "/dev/kfd:/dev/kfd"
    #   - "/dev/dri:/dev/dri"
    # Otherwise, stick with the default as it's guaranteed to run on all OSes.
    # Refer to the documentation if you've any questions:
    # https://docs.ollama.com/docker
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/ollama/ollama.all_cpu.Dockerfile
    volumes:
      - type: volume
        source: cosmic-ollama-data
        target: /root/.ollama
    ports:
      - name: cosmic-ollama-serve
        target: 11434
        host_ip: 127.0.0.1
        published: "11435"
        protocol: tcp
        app_protocol: http
        mode: host
    networks:
      - cosmic-private


volumes:
  cosmic-postgres-data:
    name: cosmic-relational
  cosmic-pgadmin-data:
    name: cosmic-gui
  cosmic-ollama-data:
    name: cosmic-slm-provider
  # NOTE: as explained above, define this only in dev (delete on prod).
  cosmic-fastapi-venv:
    name: cosmic-backend-ignore


networks:
  cosmic-public:
    name: cosmic_net
    driver: bridge
  cosmic-private:
    name: api_cosmic_net
    driver: bridge


secrets:
  cosmic-postgres-user:
    file: ./docker/secrets/database/usr.txt
  cosmic-postgres-database:
    file: ./docker/secrets/database/db.txt
  cosmic-postgres-password:
    file: ./docker/secrets/database/pwd.txt
  cosmic-pgadmin-password:
    file: ./docker/secrets/gui/pwd.txt


configs:
  cosmic-pgadmin-server:
    file: ./docker/configs/gui/svr.json
