name: OpenSI-CoSMIC


services:
  frontend:
    container_name: cosmic-react
    depends_on:
      backend:
        restart: true
        condition: service_started
        required: true

      traefik:
        restart: true
        condition: service_started
        required: true
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/react.Dockerfile
    # NOTE:
    # Live mounting for auto reload on dev only. Remove it and the
    # corresponding top-level volume on prod.
    volumes:
      - type: bind
        source: ./frontend
        target: /app
        # NOTE:
        # This makes `node_modules` directory container-native at runtime and not
        # trying to bypass the ignore at build time. This's very important when
        # you do the development in Windows.
      - type: volume
        source: cosmic-react-node
        target: /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`cosmic.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadBalancer.server.port=5173"
    networks:
        - cosmic-proxy


  backend:
    container_name: cosmic-fastapi
    depends_on:
      database:
        restart: true
        condition: service_started
        required: true

      ollama:
        restart: true
        condition: service_started
        required: true

      traefik:
        restart: true
        condition: service_started
        required: true
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/fastapi.Dockerfile
    # NOTE:
    # Live mounting for auto reload on dev only. Remove it and the
    # corresponding top-level volume on prod.
    volumes:
      - type: bind
        source: ./backend
        target: /app
        # NOTE:
        # This makes `.venv` directory container-native at runtime and not
        # trying to bypass the ignore at build time. This's very important when
        # you do the development in Windows.
      - type: volume
        source: cosmic-fastapi-venv
        target: /app/.venv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.cosmic.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadBalancer.server.port=8000"
    networks:
        - cosmic-proxy


  database:
    container_name: cosmic-postgres
    depends_on:
      traefik:
        restart: true
        condition: service_started
        required: true
    restart: unless-stopped
    # Set shared memory limit when using docker compose
    shm_size: 128mb
    secrets:
      - source: cosmic-postgres-user
        target: usr.txt
      - source: cosmic-postgres-database
        target: db.txt
      - source: cosmic-postgres-password
        target: pwd.txt
    environment:
        POSTGRES_USER_FILE: /run/secrets/usr.txt
        POSTGRES_DB_FILE: /run/secrets/db.txt
        POSTGRES_PASSWORD_FILE: /run/secrets/pwd.txt
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/postgres.Dockerfile
    volumes:
      - type: volume
        source: cosmic-postgres-data
        target: /var/lib/postgresql
    networks:
        - cosmic-proxy


  gui:
    container_name: cosmic-pgadmin
    depends_on:
      backend:
        restart: true
        condition: service_started
        required: true

      database:
        restart: true
        condition: service_started
        required: true

      traefik:
        restart: true
        condition: service_started
        required: true
    restart: unless-stopped
    secrets:
      - source: cosmic-pgadmin-password
        target: pwd.txt
    environment:
        # NOTE: Make sure to enable 2FA for this account on prod
        PGADMIN_DEFAULT_EMAIL: opensi@canberra.edu.au
        PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pwd.txt
    configs:
      - source: cosmic-pgadmin-server
        target: /pgadmin4/servers.json
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/pgadmin.Dockerfile
    volumes:
      - type: volume
        source: cosmic-pgadmin-data
        target: /var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gui.rule=Host(`db.cosmic.localhost`)"
      - "traefik.http.routers.gui.entrypoints=web"
      - "traefik.http.services.gui.loadBalancer.server.port=80"
    networks:
        - cosmic-proxy


  ollama:
    container_name: cosmic-ollama
    depends_on:
      traefik:
        restart: true
        condition: service_started
        required: true
    restart: unless-stopped
    # NOTE:
    # If you've GPU installed on your machine AND it's running Linux/MacOS
    # (this's very important), comment out current Dockerfile and use the
    # following:
    # 1. NVIDIA GPU
    # build:
    #   context: ./
    #   dockerfile: ./docker/dockerfile/ollama/ollama.nvida_cpu.Dockerfile
    # model:
    #   gpus: all
    # 2. AMD GPU
    # build:
    #   context: ./
    #   dockerfile: ./docker/dockerfile/ollama/ollama.amd_cpu.Dockerfile
    # devices:
    #   - "/dev/kfd:/dev/kfd"
    #   - "/dev/dri:/dev/dri"
    # Otherwise, stick with the default as it's guaranteed to run on all OSes.
    # Refer to the documentation if you've any questions:
    # https://docs.ollama.com/docker
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/ollama/ollama.all_cpu.Dockerfile
    volumes:
      - type: volume
        source: cosmic-ollama-data
        target: /root/.ollama
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama.rule=Host(`ollama.cosmic.localhost`)"
      - "traefik.http.routers.ollama.entrypoints=web"
      - "traefik.http.services.ollama.loadBalancer.server.port=11434"
    networks:
        - cosmic-proxy


  traefik:
    container_name: cosmic-traefik
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/traefik.Dockerfile
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - name: cosmic-traefik-http
        target: 80
        host_ip: 127.0.0.1
        published: "80"
        protocol: tcp
        app_protocol: http
        mode: host

      - name: cosmic-traefik-dashboard
        target: 8080
        host_ip: 127.0.0.1
        published: "8080"
        protocol: tcp
        app_protocol: http
        mode: host
    command:
      # Entrypoints
      - "--entrypoints.web.address=:80"

      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--providers.docker.network=proxy_cosmic_net"

      # API & Dashboard (NOTE: use only in dev)
      - "--api.dashboard=true"
      - "--api.insecure=true"

      # Logging
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
    networks:
      - cosmic-proxy


volumes:
  cosmic-postgres-data:
    name: cosmic-relational
  cosmic-pgadmin-data:
    name: cosmic-gui
  cosmic-ollama-data:
    name: cosmic-slm-provider
  # NOTE: as explained above, define this only in dev (delete on prod).
  cosmic-fastapi-venv:
    name: cosmic-backend-ignore
  # NOTE: as explained above, define this only in dev (delete on prod).
  cosmic-react-node:
    name: cosmic-frontend-ignore


networks:
  cosmic-proxy:
    name: proxy_cosmic_net
    driver: bridge


secrets:
  cosmic-postgres-user:
    file: ./docker/secrets/database/usr.txt
  cosmic-postgres-database:
    file: ./docker/secrets/database/db.txt
  cosmic-postgres-password:
    file: ./docker/secrets/database/pwd.txt
  cosmic-pgadmin-password:
    file: ./docker/secrets/gui/pwd.txt


configs:
  cosmic-pgadmin-server:
    file: ./docker/configs/gui/svr.json
