name: OpenSI-CoSMIC

services:
  ollama:
    container_name: cosmic-ollama
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/ollama.Dockerfile
    volumes:
      - type: volume
        source: cosmic-ollama-data
        target: /root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - name: ollama
        target: 11434
        host_ip: 127.0.0.1
        published: "11435"
        protocol: tcp
        app_protocol: http
        mode: host
    networks:
      - cosmic

  cosmic:
    container_name: cosmic-fastapi
    depends_on:
      ollama:
        restart: true
        condition: service_started
        required: true
      qdrant:
        restart: true
        condition: service_started
        required: true
      # pycapsule:
      #   restart: true
      #   condition: service_started
      #   required: true
    restart: unless-stopped
    # image: opensicbr/cosmic:latest
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/fastapi.Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      # - type: volume
      #   source: open-webui
      #   target: /app/backend/data
      - type: volume
        source: cosmic-configs
        target: /app/scripts/configs
        # NOTE:
        # Live mounting for auto reload on dev only. Remove it and the
        # corresponding top-level volume on prod.
      - type: bind
        source: ./
        target: /app
        # NOTE:
        # This makes `.venv` directory container-native at runtime and not
        # trying to bypass the ignore at build time. This's very important when
        # you do the development in Windows.
      - type: volume
        source: cosmic-fastapi-venv
        target: /app/.venv
    tty: true
    # NOTE: For quick debugging (on dev only)
    ports:
      - name: cosmic-uvicorn
        target: 3000
        host_ip: 127.0.0.1
        published: "3000"
        protocol: tcp
        app_protocol: http
        mode: host
      - name: cosmic-debugpy
        target: 5678
        host_ip: 127.0.0.1
        published: "5678"
        protocol: tcp
        app_protocol: http
        mode: host
    networks:
      - cosmic

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - type: volume
        source: cosmic-qdrant-data
        target: /qdrant/storage
    networks:
      - cosmic
  # pycapsule:
  #   image: opensicbr/pycapsule:latest
  #   privileged: true
  #   container_name: pycapsule
  #   ports:
  #     - '8780:8780'
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - shared_mount:/app/services/Container/mount_dir/synk_mount
  #   depends_on:
  #     ollama:
  #       restart: true
  #       condition: service_started
  #       required: true
  #   networks:
  #     - cosmic

volumes:
  cosmic-ollama-data:
    name: cosmic-default-models
  cosmic-configs:
    name: cosmic-default-configs
  # NOTE: as explained above, define this only in dev (delete on prod).
  cosmic-fastapi-venv:
    name: cosmic-ignore
  cosmic-qdrant-data:
    name: cosmic-database-vector
  # cosmic-shared-mount:
  #   name: cosmic-shared-mount
  #   external: true
  # open-webui: {}
  # pipelines: {}

networks:
  cosmic:
    name: cosmic_net
    driver: bridge
    external: true
