services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
    networks:
      - cosmic_net

  cosmic_db_server:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: openwebui_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cosmic_net

  open-webui:
    build:
      context: ./../OpenWebUI-CoSMIC
      dockerfile: Dockerfile
      args:
        OLLAMA_BASE_URL: '/ollama'
    image: opensicbr/cosmic_openwebui:latest
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data #used to store the vector data base by open-webui and cosmic
    depends_on:
      - cosmic_db_server
      - ollama
      - pipelines
      - cosmic
    ports:
      - "${OPEN_WEBUI_PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      - CORS_ALLOW_ORIGIN=http://localhost:5173;http://localhost:8080
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
      - OPENAI_API_KEY=0p3n-w3bu!
      - OPENAI_API_BASE_URL=http://pipelines:9099
      - OPENSI_COSMIC_API_BASE_URL=http://localhost:3000
      - ENABLE_OAUTH_SIGNUP=true
      - MICROSOFT_CLIENT_ID=${AZURE_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - MICROSOFT_CLIENT_TENANT_ID=${AZURE_TENANT_ID}
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@cosmic_db_server:5432/openwebui_db
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - cosmic_net

  pipelines:
    # build:
    #   context: ./../pipelines-openwebui
    #   dockerfile: Dockerfile
    image: ghcr.io/open-webui/pipelines:main
    pull_policy: always
    container_name: pipelines
    volumes:
      - pipelines:/app/pipelines
    depends_on:
      - cosmic
    ports:
      - '9099:9099'
    environment:
    - OPENSI_COSMIC_API_BASE_URL=http://cosmic:3000
    - MAX_QUERIES_PER_USER=5
    - PIPELINES_URLS=https://github.com/TheOpenSI/CoSMIC/blob/production/pipelines/cosmic_pipeline.py
    tty: true
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - cosmic_net

  cosmic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cosmic
    image: opensicbr/cosmic:latest
    volumes:
      - open-webui:/app/backend/data
      - volume_configs:/app/scripts/configs
    ports:
      - '3000:3000'
      - '5678:5678' # debupy
    depends_on:
      - ollama
    tty: true
    restart: unless-stopped
    networks:
      - cosmic_net

  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - cosmic_db_server
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
    networks:
      - cosmic_net

configs:
  servers.json:
    content: |
      {
        "Servers": {
            "1": {
                "Name": "openwebui_db",
                "Group": "Servers",
                "Port": 5432,
                "Username": "${DATABASE_USER}",
                "Host": "cosmic_db_server",
                "SSLMode": "prefer",
                "MaintenanceDB": "postgres"
            }
          }
      }


volumes:
  ollama: {}
  open-webui: {}
  pipelines: {}
  volume_configs: {}
  postgres-data: {}
  pgadmin-data: {}

networks:
  cosmic_net:
    driver: bridge