[project]
name = "CoSMIC"
version = "1.0.0"
description = "Cognitive System of Machine Intelligent Computing"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chess>=1.11.2",
    "faiss-cpu>=1.13.2",
    "fastapi[standard]>=0.135.1",
    "langchain-community>=0.4.1",
    "langchain-huggingface>=1.2.1",
    "langchain-text-splitters>=1.1.1",
    "ollama>=0.6.1",
    "openai>=2.31.0",
    "pandas>=3.0.2",
    "peft>=0.18.1",
    "pypdf[crypto]>=6.10.0",
    "sentence-transformers>=5.4.0",
    "sqlmodel>=0.0.37",
    "stockfish>=5.0.0",
    "torch>=2.11.0",
    "transformers[torch]>=5.3.0",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.20",
]
