### Core modules ###
from pathlib import Path
from fastapi import (
    HTTPException,
    status
)
import uuid


### Type hints ###


### Internal modules ###
from . import chess as chess_instances
from .base import ServiceBase
from .document_index import DocumentMetadata
from .llms.LLMBase import LLMBase
from .rag import RAGBase
from ...modules.code_generation.code_generation import CodeGenerator
from .system_information_service import SystemInformationService
from .fallback_service import FallbackService
from ...utils.log_tool import set_color



class QABase(ServiceBase):
    def __init__(
        self,
        query_analyser: LLMBase,
        llm:            LLMBase,
        rag:            RAGBase,
        code_generator: CodeGenerator,
        system_information_service: SystemInformationService,
        fallback_service: FallbackService,
        config:         str | None = None,
        **kwargs
    ) -> None:
        """
        Base class for QA.

        Args:
            query_analyser (LLMBase):
                query analyser.

            llm (LLMBase):
                LLM instance.

            rag (RAGBase):
                RAG instance containing vector database service.

            code_generator (CodeGenerator):
                code generation service.

            system_information_service (SystemInformationService):
                system information service.

            fallback_service (FallbackService):
                fallback service.

            config (str, optional):
                config file to extract settings. Default to None.
        """
        super().__init__( **kwargs)

        # Set config globally.
        self.query_analyser             = query_analyser
        self.llm                        = llm
        self.rag                        = rag
        self.code_generator             = code_generator
        self.system_information_service = system_information_service
        self.fallback_service           = fallback_service

        return None


    def __call__(
        self,
        query:      str,
        # NOTE:
        # for legacy purposes. Change to `dict[int, dict[str, str]]` type when
        # update to handle `int` properly
        services:               dict[str, dict[str, str]],
        context:                str | dict          = "",
        is_rag:                 bool                = False,
        verbose:                bool                = False,
        user_id:                str | None          = None,
        session_id:             str | None          = None,
        global_service_names:   list[str] | None    = None,
        memory_service_active:  bool                = False,
        has_files:              bool                = False,
        file_refs:              list[str] | None    = None,
    ) -> tuple[str, str, int, int ,float | int]:
        """
        Process each QA.

        Args:
            query (str):
                a question.

            services (dict[str, dict[str, str]]):
                all available services for Query Analyser, which then being used
                to re-structure question with its prompting techniques.

            context (str | dict, optional):
                contex associated with the question. Defaults to "".

            is_rag  (bool, optional):
                if retrieve context for the question. Defaults to False.

            verbose (bool, optional):
                debug mode. Default to False.

        Returns:
            response (str):
                truncated answer if applicable.

            raw_response (str):
                original answer from LLM.

            input_token (int):
                total amount of input tokens captured by LLM during each
                QA process.

            output_token (int):
                total amount of output tokens generated by LLM during each
                QA process.

            retrieve_score (float | int):
                score of context retrieving (if applicable). Default to '-1' for
                non-RAG services.
        """
        # Set initial return answers.
        response:       str | None  = None
        raw_response:   str | None  = None
        input_token:    int         = 0
        output_token:   int         = 0
        retrieve_score: float | int = -1

        
        # Add default service 0
        if '0' not in services:
            services["0"] = {
                "name": "system_information",
                "desc": "Answer questions about the AI assistant itself such as who created it, what OpenSI-CoSMIC is, and what it can do."
            }

        # cut down to just "name" of the services not its "desc"
        services_name: dict[str, str] = {}
        for (service_id,service_info) in services.items():
            services_name[service_id]= service_info['name']

        # No active services found from fetched API endpoint
        if len(services_name) == 0:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail={
                    "status": "404 - Not Found",
                    "message": "{trig:s}: {cond:s}".format(
                        trig="EmptyServiceError",
                        cond="No active services found from fetched API endpoint. At least 1 service is required to for Query Analyser."
                    )
                }
            )

        # Get service option & minimal extra info about selected service through
        # `query_analyser.py`.
        (
            service_option,
            service_info_dict
        ) = self.query_analyser(
            query,
            services=services # pyright: ignore[reportCallIssue]
        )

        # The service the analyser actually chose (before any override below),
        # for debugging.
        analyser_service_option = service_option

        # A file attached while the analyser was unsure (routed to system-info 0
        # or fallback -1) still needs the retrieval branch so the file gets
        # considered. Route it to the NEUTRAL general service (4) — not the
        # academic-governance specialist (5) — so an unrelated file is not
        # forced onto the governance knowledge base/persona. Fall back to 5 only
        # if the general service is not registered.
        if has_files and service_option in ("0", "-1"):
            service_option = "4" if "4" in services_name else "5"

        # Skip query as required or unknown service option.
        if query.find("skip") > -1:
            return (
                str(response),
                str(raw_response),
                input_token,
                output_token,
                retrieve_score
            )

        # Validate the prefix is an 8-char hex file_id to avoid malformed ref silently breaks retrieval 
        # document_ids target retrieval at the attached file
        # attached_file_names tell the LLM which file the question is about
        document_ids: List[str] = []
        attached_file_names: List[str] = []
        for ref in (file_refs or []):
            parts = ref.split("_", 1)
            doc_id = parts[0]
            if len(doc_id) == 8 and all(c in "0123456789abcdef" for c in doc_id):
                document_ids.append(doc_id)
                raw_name = parts[1] if len(parts) > 1 else ref
                attached_file_names.append(raw_name)
            else:
                print(f"[qa] WARNING: unparseable file ref '{ref}' (no 8-hex file_id); skipping.")

        # Is this turn directed at an attached file? (explicit reference words,
        # or a "summarise" request). We detect it here so a file-directed
        # follow-up that carries NO fresh attachment ("summarise it") can be
        # resolved back to the file the user attached earlier in this session.
        _ql = query.lower()
        FILE_INTENT_MARKERS = (
            "this file", "the file", "this document", "the document",
            "this doc", "the doc", "this pdf", "the pdf",
            "this paper", "the paper", "this report", "the report",
            "attached", "attachment", "uploaded",
            "summarise", "summarize", "summary",
        )
        file_directed: bool = any(m in _ql for m in FILE_INTENT_MARKERS)

        # File-directed but nothing re-attached this turn: fall back to the
        # files already indexed under this session (attached earlier). Their
        # chunks are session-scoped to this user, so this stays isolated.
        if file_directed and not document_ids and user_id and session_id:
            try:
                session_docs = self.rag.vector_database.get_session_document_ids(
                    user_id, session_id
                )
            except Exception as exc:  # pragma: no cover - defensive
                session_docs = []
                print(f"[qa] WARNING: session document lookup failed: {exc}")
            for doc_id, name in session_docs:
                document_ids.append(doc_id)
                attached_file_names.append(name)

        # NOTE: "the attached file" / "this document" always refers to the file
        # the user attached in the UI for this turn (or resolved from the session
        # above) — NOT to any document the query merely *names*. So a question
        # like "what does the Academic Governance Handbook say ...?" is a
        # knowledge-base question, not a file-directed one, even if an attached
        # file happens to share that name. We therefore rely only on the explicit
        # reference markers above and do NOT treat a filename mention as
        # file-directed.

        # DANGLING file reference: the query refers to "the attached file" but
        # none is actually present — nothing attached this turn (`has_files`) and
        # no session file resolved above (`document_ids` still empty). The global
        # knowledge base is NOT the user's attached file, so we must not let it be
        # used as one. Flag it so the answer says the file is missing and asks the
        # user to attach it, instead of silently substituting a KB document.
        dangling_file_reference: bool = (
            file_directed and not has_files and not document_ids
        )

        # Which knowledge base (if any) does this query want? Use the query
        # analyser's own routing decision, not keyword matching: the analyser
        # is an intent classifier that already picked the service this query is
        # about, and each service carries a `memory_capability` flag (surfaced
        # here as membership of `global_service_names`, the active
        # memory-capable services). If the query is routed to a memory-capable
        # service, that service's knowledge base is the one to consult — even
        # when the reranker scores it low, because intent (routing) beats a weak
        # similarity score. This scales to any number of services with no
        # per-service configuration: add a memory-capable service and the
        # router routes to it automatically.
        routed_service_name: str = services_name.get(service_option, "")
        routed_to_kb: bool = routed_service_name in (global_service_names or [])

        # Process query with service parsing.
        if service_option.find("1.") > -1:
            if service_option == "1.0":
                # Set game move mode.
                move_mode = (
                    "algebric"
                    if   (context == "")
                    else (context)
                )

                # Get chess FEN.
                current_fen = service_info_dict["fen"]

                # TODO:
                # this will be updated again once we've service-specific configs
                # implemented
                binary_path: str = str(
                    Path(__file__).resolve(strict=True).parent.parent.parent.joinpath(
                        "third_party",
                        "stockfish",
                        "stockfish-ubuntu-x86-64-avx2"
                    )
                )

                next_move_predictor = chess_instances.StockfishFENNextMove(binary_path=binary_path)

                # Predict the next move.
                next_move = next_move_predictor(
                    fen=current_fen,
                    move_mode=str(object=move_mode),
                    topk=5
                )

                # Set the response with question and next move.
                move_prediction_context = f"The current chess FEN is {[current_fen]}."

            # this is for prediction given moves, service_option == "1.1":
            else:
                # Set game move mode.
                move_mode = (
                    "algebric"
                    if   (context == "")
                    else (context)
                )

                # Get moves.
                current_moves = service_info_dict["moves"]

                # TODO:
                # this will be updated again once we've service-specific configs
                # implemented
                binary_path: str = str(
                    Path(__file__).resolve(strict=True).parent.parent.parent.joinpath(
                        "third_party",
                        "stockfish",
                        "stockfish-ubuntu-x86-64-avx2"
                    )
                )

                next_move_predictor = chess_instances.StockfishSequenceNextMove(binary_path=binary_path)

                # Predict the next move.
                next_move = next_move_predictor(
                    moves=current_moves,
                    move_mode=str(object=move_mode),
                    topk=5
                )

                # Set the response with question and next move.
                move_prediction_context = f"The previous chess moves are {[current_moves]}."

            # Explain why these moves are feasible.
            user_prompt = f"Select the best next move from {next_move} and explain why it is the best."
            (
                response,
                raw_response,
                input_token,
                output_token
            ) = self.llm(
                question=user_prompt,
                context=move_prediction_context
            )

            # Attach all the moves in case LLM cannot select the best one.
            response        = f"The next moves are from {next_move}.\n{response}"
            raw_response    = f"The next moves are from {next_move}.\n{raw_response}"

        elif service_option == "2":
            selected_service_name = services_name.get(service_option, "").lower()

            if (
                memory_service_active
                and (selected_service_name == "memory")
                and (user_id)
            ):
                payload = DocumentMetadata(
                    document_id=uuid.uuid4().hex[:8],
                    user_id=user_id,
                    memory_type="user",
                ).to_vector_payload()

                self.rag.vector_database.update_database_from_text(
                    text=query,
                    extra_metadata=payload
                )

                response = raw_response = "Saved to your memory."

        elif service_option == "3":
            (
                raw_response,
                response
            )= self.code_generator(query)


        # Add system information service 
        elif service_option == "0":
            (
                response,
                raw_response,
                input_token,
                output_token
            ) = self.system_information_service(
                query=query,
                services=services,
                context=context
            )

        # When all services are disabled and service 0 cannot answer, query analyser will return -1
        elif service_option == "-1":
            response, raw_response = self.fallback_service(services=services)

        else:
            # Retrieval runs when the query is routed to a memory-capable
            # service (metadata-driven — any such service, not a hardcoded id),
            # or a file is involved (freshly attached, or a file-directed
            # follow-up resolved to a session file).
            execute_rag = (
                (is_rag) and
                (routed_to_kb
                 or has_files
                 or bool(document_ids))
            )

            # Origins of retrieved context, for citing sources in the answer.
            retrieved_sources: list = []
            # Whether the attached file contributed context to this answer.
            answered_from_file: bool = False
            # Retrieved context text (empty on the non-RAG path).
            context_retrieved: str = ""
            # The persona (system prompt) that will actually answer this turn.
            answering_service: str = services_name.get(service_option, "")

            if execute_rag:
                # Check if context is chat hostory
                chat_history_context = (
                    context
                    if   ("Conversation History:" in context)
                    else ("")
                )

                rag_context = (
                    ""
                    if   ("Conversation History:" in context)
                    else (context)
                )

                # If retrieving context, first generate the user prompt given the
                # user prompter format.
                user_prompt = self.llm.user_prompter(
                    query,
                    context=rag_context
                ) # pyright: ignore[reportCallIssue]

                # Get the retrieved context, scoped to the active memory tiers.
                # `retrieved_sources` describes where each selected chunk came
                # from (session/user/global + title) so the final answer can
                # cite its sources and attribute the winning tier correctly.
                #
                # An explicitly attached file is an intent signal, not just
                # another candidate: the user is pointing at that document. So
                # when document_ids are present we GUARANTEE the attached file's
                # chunks into the context and MERGE the rest of memory on top —
                # a generic question ("summarise this") is answered from the
                # file, while a question relating it to the knowledge base ("how
                # does this align with the governance policies?") gets BOTH the
                # file and the relevant policy chunks in one answer. With no
                # file, this is a plain union over the active memory tiers.
                if document_ids:
                    # `file_directed` (computed above) says whether the question
                    # points at the file. When True the file is guaranteed into
                    # the answer even for generic phrasing ("summarise it"); when
                    # False it is included only if actually relevant, so a pure
                    # domain question with a stale attachment is answered from
                    # the knowledge base and does not cite the file.
                    (
                        context_retrieved,
                        retrieve_score,
                        retrieved_sources
                    ) = self.rag.retrieve_with_attachment(
                        query,
                        user_id=user_id,
                        session_id=session_id,
                        global_service_names=global_service_names,
                        document_ids=document_ids,
                        include_user=memory_service_active,
                        include_global=True,
                        file_directed=file_directed,
                        force_kb=routed_to_kb,
                        kb_service_name=routed_service_name if routed_to_kb else None,
                    )
                else:
                    (
                        context_retrieved,
                        retrieve_score,
                        retrieved_sources
                    ) = self.rag( # pyright: ignore[reportAssignmentType]
                        query,
                        user_id=user_id,
                        session_id=session_id,
                        global_service_names=global_service_names,
                        include_session=True,
                        include_user=memory_service_active,
                        include_global=True,
                        document_ids=None,
                    )

                # Whether the attached file actually contributed any chunk to the
                # merged context (its chunks are guaranteed first when present).
                answered_from_file = bool(document_ids) and any(
                    s["tier"] == "session" for s in retrieved_sources
                )

                # Choose the answering persona.
                #  - If the query analyser routed to a SPECIFIC specialist
                #    service (e.g. academic_governance), use THAT service's
                #    persona — the analyser decided the query is about that
                #    domain, so it should answer as that specialist.
                #  - Only fall back to the neutral document-QA persona when a
                #    file genuinely contributed AND the route is a generic /
                #    non-specialist service (general 4, system-info 0, fallback
                #    -1) that has no persona of its own — so a plain document
                #    question isn't answered by a bland/empty prompt.
                answering_service = (
                    "document_qa"
                    if answered_from_file and service_option in ("0", "-1", "4")
                    else services_name.get(service_option, "")
                )

                # --- debug: final context + persona handed to the LLM (grep "[qa]") ---
                from collections import Counter as _Counter
                print(
                    f"[qa] CONTEXT analyser_service={analyser_service_option!r}"
                    f"({services_name.get(analyser_service_option, '')}) "
                    f"routed_service={service_option!r}({services_name.get(service_option, '')}) "
                    f"persona={answering_service!r} "
                    f"routed_to_kb={routed_to_kb} "
                    f"file_directed={file_directed} docs={document_ids or None} "
                    f"tiers={dict(_Counter(s['tier'] for s in retrieved_sources))} "
                    f"scores={[round(s['score'], 4) for s in retrieved_sources]} "
                    f"ctx_chars={len(context_retrieved)} q={query[:60]!r}"
                )

                # Only claim "answered from your attached file" when the file
                # actually contributed context — otherwise the answer came from
                # user/global memory and crediting the attached file would be
                # false (e.g. an attached file unrelated to the query).
                file_note = (
                    f"The user attached the file(s): {', '.join(attached_file_names)}. "
                    "Answer using the retrieved context from that file.\n"
                    if attached_file_names and answered_from_file else ""
                )

                # The query mentions an attached file but none is present: tell
                # the LLM explicitly so it does NOT treat the knowledge-base
                # context below as the user's attached file.
                if dangling_file_reference:
                    file_note += (
                        "IMPORTANT: the user's message refers to an attached "
                        "file, but NO file is attached to this conversation. The "
                        "Context below is from the shared knowledge base, which "
                        "is NOT the user's attached file. Answer only the parts "
                        "you can from that context, and for anything that "
                        "requires the user's file, state that no file is attached "
                        "and ask them to attach it.\n"
                    )

                # Remain the other variables in context if it is a dictionary,
                # otherwise overwrite it.
                suffix = (
                    ""
                    if   (context_retrieved == "")
                    else (f"\n{file_note}Context:\n {context_retrieved}")
                )

                context = (
                    context.update({"context": f"{chat_history_context}{suffix}"})
                    if   (isinstance(context, dict))
                    else (f"{chat_history_context}{suffix}")
                ) # pyright: ignore[reportAssignmentType]
            
            # Non-RAG services (or when RAG is disabled) fall through here.
            else:
                user_prompt     = query
                retrieve_score  = -1

            # `answering_service` (the persona) was chosen above when RAG ran; on
            # the non-RAG path it defaults to the routed service's persona.

            # Get the response with retrieved context if applicable.
            (
                response,
                raw_response,
                input_token,
                output_token
            ) = self.llm(
                question=user_prompt,
                context=context,
                service_name=answering_service
            )

            # If a file was attached but this answer did NOT use it (the question
            # was about something else), acknowledge the file and offer to use
            # it — so ignoring it reads as a deliberate choice, and the user is
            # nudged to ask about the file if that's what they meant. Only when
            # the answer actually produced retrieved context from the knowledge
            # base (there was something to answer from).
            if attached_file_names and not answered_from_file and context_retrieved:
                _names = ", ".join(attached_file_names)
                response = (
                    f"{response}\n\n_You also attached {_names}, but this answer "
                    f"is from the knowledge base — your question wasn't about that "
                    f"file. Would you like a summary of {_names}, or an answer to "
                    f"something specific in it?_"
                )

            # The query referred to an attached file, but none is attached. Tell
            # the user plainly (the knowledge base is not their file) and ask
            # them to attach it for the part that needs it.
            if dangling_file_reference:
                response = (
                    f"{response}\n\n_You referred to an attached file, but no "
                    f"file is attached to this chat. I've answered from the "
                    f"knowledge base where I could — please attach the file so I "
                    f"can use it for the part of your question that needs it._"
                )

            # Cite where the retrieved information came from. Sources are listed
            # in relevance order; each line names the tier and the source title
            # (attached file name, or the global service it came from), so the
            # user can see which parts of the answer are grounded in their file,
            # their saved memory, or the global knowledge base.
            if retrieved_sources:
                seen: set = set()
                lines: list[str] = []
                for src in retrieved_sources:
                    key = (src["tier"], src["title"], src["service_name"])
                    if key in seen:
                        continue
                    seen.add(key)

                    label = src["label"]
                    if src["tier"] == "global" and src["service_name"]:
                        label = f"{label} ({src['service_name']})"

                    title = src["title"] or "(untitled)"
                    lines.append(f"- {label}: {title}")

                response = f"{response}\n\nSources:\n" + "\n".join(lines)

        # NOTE:
        # Last step to transfer final response with some extra info (I/O
        # token, retrieve score, etc) over to `opensi_cosmic.py`. This's the
        # 2nd time QA sent user query + selected service prompt (from
        # `query_analyser.py`). The latter is different based on which condition
        # above get hit

        # Sum up I/O tokens from 1st Ollama call (in `service_info_dict`) with
        # I/O tokens from 2nd Ollama call (in either condition above)
        total_input_token:  int = service_info_dict["input_token"] + input_token
        total_output_token: int = service_info_dict["output_token"] + output_token

        return (
            str(response),
            str(raw_response),
            total_input_token,
            total_output_token,
            retrieve_score
        )
