### Core modules ###


### Type hints ###


### Internal modules ###
from ..query_analyser.user_prompt import QueryAnalyserSystemInfo
from .llms.LLMBase import LLMBase
from .base import ServiceBase



class SystemInformationService(ServiceBase):
    def __init__(
        self,
        llm: LLMBase,
        **kwargs
    ) -> None:
        """
        Service 0: answer questions about the OpenSI-CoSMIC system itself.

        Args:
            llm (LLMBase):
                initiate with LLM instance to answer system-info queries.
        """

        super().__init__(**kwargs)

        self.llm = llm

        return None


    def __call__(
        self,
        query:      str,
        services:   dict,
        context:    str | dict = ""
    ) -> tuple[str, str, int, int]:
        """
        Answer a system-information query about OpenSI-CoSMIC.

        Args:
            query (str):
                user query.

            services (dict):
                current services dict, used to describe capabilities. Important
                for accessing: QueryAnalyserSystemInfo()

            context (str | dict, optional):
                existing context (e.g. chat history). Defaults to "".

        Returns:
            response (str):
                truncated answer.

            raw_response (str):
                original answer from LLM.

            input_token (int):
                amount of input tokens captured by LLM for each QA process that
                involve service 0.

            output_token (int):
                amount of output tokens generated by LLM for each QA process that
                involve service 0.
        """
        user_prompt: str = query

        # If the question is related to system information,
        # add system information to context.

        system_information: str = QueryAnalyserSystemInfo(services).system_information


        # Add the information to existing context.
        # This context is likely to be chat history.

        if isinstance(context, dict):
            context["context"] = "OpenSI System Information:\n" + system_information + "\n\n" + context["context"]
        else:
            context = "OpenSI System Information:\n" + system_information + "\n\n" + context

        # NOTE:
        # This's where QA sent user query + selected service prompt (from
        # `query_analyser.py`) to Ollama. For this case, we hit service 0

        ( # pyright: ignore[reportAssignmentType]
            response,
            raw_response,
            input_token,
            output_token
        ) = self.llm(
            user_prompt,
            context=context,
            service_name="system_information"
        )

        return (
            response,
            raw_response,
            input_token,
            output_token
        )
