name: CoSMIC

services:
  frontend:
    container_name: cosmic-react
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/dockerfile/react.Dockerfile
    ports:
      - name: cosmic-vite
        target: 5173
        host_ip: 127.0.0.1
        published: "5174"
        protocol: tcp
        app_protocol: http
        mode: host
    networks:
        - cosmic-public

  backend:
    container_name: cosmic-fastapi
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/dockerfile/fastapi.Dockerfile
    ports:
      - name: cosmic-uvicorn
        target: 8000
        host_ip: 127.0.0.1
        published: "8001"
        protocol: tcp
        app_protocol: http
        mode: host
    networks:
        - cosmic-public
        - cosmic-private

  database:
    container_name: cosmic-postgres
    depends_on:
      backend:
        restart: true
        condition: service_started
        required: true
    restart: unless-stopped
    # Set shared memory limit when using docker compose
    shm_size: 128mb
    secrets:
      - source: cosmic-postgres-user
        target: postgres_user
      - source: cosmic-postgres-db
        target: postgres_db
      - source: cosmic-postgres-password
        target: postgres_password
    environment:
        POSTGRES_USER_FILE: /run/secrets/postgres_user
        POSTGRES_DB_FILE: /run/secrets/postgres_db
        POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    build:
      context: ./
      dockerfile: ./docker/dockerfile/postgres.Dockerfile
    volumes:
      - type: volume
        source: cosmic-postgres-data
        target: /var/lib/postgresql
        volume:
          nocopy: false
    # NOTE: Open to quickly connect and debug on dev only
    ports:
      - name: cosmic-postgres-psql
        target: 5432
        host_ip: 127.0.0.1
        published: "5433"
        protocol: tcp
        app_protocol: http
        mode: host
    networks:
        - cosmic-private

  gui:
    container_name: cosmic-pgadmin
    depends_on:
      backend:
        restart: true
        condition: service_started
        required: true
      database:
        restart: true
        condition: service_started
        required: true
    restart: unless-stopped
    secrets:
      - source: cosmic-pgadmin-password
        target: pgadmin_password
    environment:
        # NOTE: Make sure to enable 2FA for this account on prod
        PGADMIN_DEFAULT_EMAIL: opensi@canberra.edu.au
        PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    configs:
      - source: cosmic-pgadmin-server
        target: /pgadmin4/servers.json
    build:
      context: ./
      dockerfile: ./docker/dockerfile/pgadmin.Dockerfile
    volumes:
      - type: volume
        source: cosmic-pgadmin-data
        target: /var/lib/pgadmin
        volume:
          nocopy: false
    ports:
      - name: cosmic-pgadmin-gunicorn
        target: 80
        host_ip: 127.0.0.1
        published: "5050"
        protocol: tcp
        app_protocol: http
        mode: host
    networks:
      - cosmic-private

volumes:
  cosmic-postgres-data:
    name: cosmic-relational
  cosmic-pgadmin-data:
    name: cosmic-gui

networks:
  cosmic-public:
    name: cosmic_net
    driver: bridge
  cosmic-private:
    name: api_cosmic_net
    driver: bridge

secrets:
  cosmic-postgres-user:
    file: ./docker/secret/postgres_user.txt
  cosmic-postgres-db:
    file: ./docker/secret/postgres_db.txt
  cosmic-postgres-password:
    file: ./docker/secret/postgres_password.txt
  cosmic-pgadmin-password:
    file: ./docker/secret/pgadmin_password.txt

configs:
  cosmic-pgadmin-server:
    file: ./docker/config/pgadmin_servers.json
