chess:
  stockfish_path: ''
doc_directory: ''
document_path: []
is_quantized: false
llm_name: ollama:qwen3.5:0.5b
query_analyser:
  is_quantized: false
  llm_name: ollama:llama3.1:8b
rag:
  retrieve_score_threshold: 0.7
  topk: 10
  vector_db_path: backend/data/vector_db_cosmic
seed: 0
service: -1
