"""initial schema

Revision ID: b3ed4b5451ce
Revises: 
Create Date: 2025-06-12 15:53:52.586955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from internal.models import Service, Config


# revision identifiers, used by Alembic.
revision: str = 'b3ed4b5451ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'services',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('value', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=True)
    op.create_index(op.f('ix_services_value'), 'services', ['value'], unique=True)


    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('openweb_id', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('role', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_openweb_id'), 'users', ['openweb_id'], unique=True)


    op.create_table(
        'configs',
        sa.Column('id', sa.Integer(), autoincrement='ignore_fk', nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('service_id', sa.Integer(), nullable=True),
        sa.Column('chess_path', sa.String(), nullable=True),
        sa.Column('doc_directory', sa.String(), nullable=True),
        sa.Column('is_quantized', sa.Boolean(), nullable=True),
        sa.Column('llm_name', sa.String(), nullable=True),
        sa.Column('qa_is_quantized', sa.Boolean(), nullable=True),
        sa.Column('qa_llm_name', sa.String(), nullable=True),
        sa.Column('rag_retrieve_score_threshold', sa.Float(), nullable=True),
        sa.Column('rag_topk', sa.Integer(), nullable=True),
        sa.Column('rag_vector_db_path', sa.String(), nullable=True),
        sa.Column('same_as_above', sa.Boolean(), nullable=True),
        sa.Column('seed', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_configs_id'), 'configs', ['id'], unique=True)


    op.create_table(
        'statistics',
        sa.Column('id', sa.Integer(), autoincrement='ignore_fk', nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('start_date', sa.DateTime(), nullable=True),
        sa.Column('last_date', sa.DateTime(), nullable=True),
        sa.Column('average_token_length', sa.Integer(), nullable=True),
        sa.Column('query_count', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_statistics_id'), 'statistics', ['id'], unique=True)
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = Session(bind=bind)

    # Seed services
    if session.query(sa.exists().where(Service.value == -1)).scalar() is False:
        session.add_all([
            Service(title="Auto-selection (default)", value= -1),
            Service(title="Chess", value=0),
            Service(title="Update Vector Database", value=1),
            Service(title="Code Generation", value=2),
            Service(title="General Question Answering", value=3),
        ])
    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_id'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_index(op.f('ix_configs_id'), table_name='configs')
    op.drop_table('configs')
    op.drop_index(op.f('ix_users_openweb_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_value'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
