### Core modules ###
from sqlmodel import Field, text
from uuid import uuid7


### Type hints ###
from datetime import datetime
from uuid import UUID


### Internal modules ###
from ..models import RoleBase


# NOTE:
# + SQLModel doesn't give a fuck for custom types from both of its wrapper so
#   correctly type-hints it also fucked as well HAHA.
#
# + Python linter (pyright) also fucked with this crap as well HAHA. I don't
#   care anymore, just slap in `type: ignore` and called it a day.


class Roles(RoleBase, table=True):
    """docstring for Roles."""
    # Postgres will generate the UUID (version 7) for us instead of manual
    # defining it. The way this works in SQLModel is to provide value to both
    # type-hint and `default` param
    id: UUID | None = Field(
        default=None,
        nullable=False,
        # For some fucking reasons, SQLModel works perfectly fine with PK
        # constraint. For fuck sake!
        primary_key=True,
        sa_column_kwargs={
            "server_default": text(text="uuidv7()")
        }
    )
    # Postgres will generate the UUID (version 7) for us instead of manual
    # defining it. The way this works in SQLModel is to provide value to both
    # type-hint and `default` param
    user_id: UUID | None = Field(
        default=None,
        nullable=False,
        # Disable it unless you're fine with the default constraint configs
        # because SQLModel is shit.
        foreign_key=False,
        sa_column_kwargs={
            "server_default": text(text="uuidv7()")
        }
    )
    # Postgres will generate the datetime (timestamp without time zone) for us
    # instead of manual defining it. The way this works in SQLModel is to
    # provide value to both type-hint and `default` param
    create_on: datetime | None = Field(
        default=None,
        nullable=False,
        sa_column_kwargs={
            "server_default": text(text="localtimestamp(2)")
        }
    )


class RolePublic(RoleBase):
    """docstring for RolePublic."""
    # Hint for testers that these columns will not be appear in body as it is
    # generated by database
    id: UUID
    user_id: UUID
    create_on: datetime


class RoleCreate(RoleBase):
    """docstring for RoleCreate."""
    # Hint for testers that these columns are needed alongside with default one
    # during a POST request
    user_id: UUID = Field(
        default=uuid7(),
        nullable=False
    )


class RoleUpdate(RoleBase):
    """docstring for RoleUpdate."""
    # Hint for testers that these columns are needed (optionally) alongside with
    # default one during a PATCH request
    name:   str | None = None # type: ignore
    desc:   str | None = None
