### Core modules ###
from sqlmodel import Field, Relationship, text


### Type hints ###
from datetime import datetime
from uuid import UUID
from sqlalchemy.sql.sqltypes import TIMESTAMP
from typing_extensions import Optional # SQLModel is being a bitch here, once again


### Internal modules ###
from ..models import UserBase
from .roles import RolePublic


# NOTE:
# + SQLModel doesn't give a fuck for custom types from both of its wrapper so
#   correctly type-hints it also fucked as well HAHA.
#
# + Python linter (pyright) also fucked with this crap as well HAHA. I don't
#   care anymore, just slap in `type: ignore` and called it a day.


class Users(UserBase, table=True):
    """docstring for Users."""
    # TODO: implement hashed password
    password: str = Field(
        max_length=256
    )
    # Postgres will generate the UUID (version 7) for us instead of manual
    # defining it. The way this works in SQLModel is to provide value to both
    # type-hint and `default` param
    id: UUID | None = Field(
        default=None,
        nullable=False,
        # For some fucking reasons, SQLModel works perfectly fine with PK
        # constraint. For fuck sake!
        primary_key=True,
        sa_column_kwargs={
            "server_default": text(text="uuidv7()")
        }
    )
    # Postgres will generate the timestamp (with timezone) for us instead of
    # manual defining it. The way this works in SQLModel is to provide value to
    # both type-hint and `default` param
    created_on: datetime | None = Field(
        default=None,
        nullable=False,
        sa_type=TIMESTAMP(timezone=True), # type: ignore
        sa_column_kwargs={
            "server_default": text(text="current_timestamp(2)")
        }
    )

    ### It's very confusing to read from database perspective, but here's my attempt:
    ###   "CoSMIC user have Admin role granted through `assigned_to` object-level connection"
    ###      👆              👆          👆                 👆                        👆
    ###    Users            Users       Users           Relationship             Relationship
    ###                   type-hint    object         `back_populates`
    granted: Optional["Roles"] = Relationship(
        back_populates="assigned_to",
        sa_relationship_kwargs={
            "uselist": False
        },
        cascade_delete=True
    )


class UserPublic(UserBase):
    """docstring for UserPublic."""
    # Hint for testers that these columns will not be appear in body as it is
    # generated by database
    password: str # TODO: implement hashed password
    id: UUID
    created_on: datetime


class UserPublicWithRole(UserPublic):
    """docstring for UserPublicWithRole."""
    # Hint for testers that these are Relationship Attributes (FK) value (GET
    # request scenario), which modifiable via the Role API only
    granted: RolePublic | None = None


class UserCreate(UserBase):
    """docstring for UserCreate."""
    # Hint for testers that these columns are needed alongside with default one
    # during a POST request
    # TODO: implement hashed password
    password: str


class UserUpdate(UserBase):
    """docstring for UserUpdate."""
    # Hint for testers that these columns are needed (optionally) alongside with
    # default one during a PATCH request
    name:       str | None = None # type: ignore
    email:      str | None = None
    # TODO: implement hashed password
    password:   str | None = None # type: ignore


class UserDelete(UserBase):
    """docstring for UserDelete."""
    # Hint for testers that this is the response message for DELETE request
    id: UUID
    created_on: datetime
    response: dict[str, int | str] | None = {
        "status": 200,
        "message": "User deleted successfully."
    }
