### Core modules ###
from sqlmodel import Field, text


### Type hints ###
from datetime import datetime
from uuid import UUID
from sqlalchemy.sql.sqltypes import TIMESTAMP


### Internal modules ###
from ..models import UserBase


# NOTE:
# + SQLModel doesn't give a fuck for custom types from both of its wrapper so
#   correctly type-hints it also fucked as well HAHA.
#
# + Python linter (pyright) also fucked with this crap as well HAHA. I don't
#   care anymore, just slap in `type: ignore` and called it a day.


class Users(UserBase, table=True):
    """docstring for Users."""
    # Postgres will generate the UUID (version 7) for us instead of manual
    # defining it.
    id: UUID | None = Field(
        default=None,
        primary_key=True,
        nullable=False,
        sa_column_kwargs={
            "server_default": text(text="uuidv7()")
        }
    )
    # Postgres will generate the datetime (timestamp with time zone) for us
    # instead of manual defining it
    create_on: datetime | None = Field(
        default=None,
        nullable=False,
        sa_type=TIMESTAMP(timezone=True), # type: ignore
        sa_column_kwargs={
            "server_default": text(text="current_timestamp(2)")
        }
    )


class UserPublic(UserBase):
    """docstring for UserPublic."""
    # Hint for testers that these columns will not be appear in body as it is
    # generated by database
    id: UUID
    create_on: datetime


class UserCreate(UserBase):
    """docstring for UserCreate."""
    # Hint for testers that these columns are needed alongside with default one
    # during a POST request
    pass


class UserUpdate(UserBase):
    """docstring for UserUpdate."""
    # Hint for testers that these columns are needed (optionally) alongside with
    # default one during a PATCH request
    name:       str | None = None # type: ignore
    email:      str | None = None
    password:   str | None = None # type: ignore
